sonar.projectKey=olevelstarsbd
sonar.projectName=OLevelStars
sonar.projectVersion=1.0

sonar.sources=frontend/src,backend/src,backend/scripts
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**,**/.next/**,**/Dockerfile,**/.dockerignore,**/docker-compose*.yml,**/*.min.js

sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info,backend/coverage/lcov.info
